//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoIgreja.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class evento
    {
        public int idevento { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string descricao { get; set; }
        public string nome { get; set; }
        public string local { get; set; }
        public int agenda_idagenda { get; set; }
    
        public virtual agenda agenda { get; set; }
    }
}
